# Generated by Django 5.2.3 on 2025-06-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0004_remove_booking_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='methods',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank'), ('mobile', 'Mobile')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], max_length=20),
        ),
    ]
