# Generated by Django 5.2.3 on 2025-06-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0005_alter_payment_methods_alter_payment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
