# Generated by Django 5.2.3 on 2025-07-05 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0009_tour_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
