# Generated by Django 5.2.3 on 2025-06-16 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date', models.DateTimeField()),
                ('recipient_type', models.CharField(max_length=50)),
                ('recipient_id', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parent_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'parent',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('methods', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('payment_date', models.DateField()),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('tour_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('destination', models.TextField()),
            ],
            options={
                'db_table': 'tour',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('staff', 'Staff'), ('parent', 'Parent')], max_length=10)),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('notification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapp.notification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tourapp.user')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('classes', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapp.parent')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapp.tour')),
            ],
            options={
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_date', models.DateField()),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapp.payment')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapp.student')),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapp.tour')),
            ],
            options={
                'db_table': 'registration',
            },
        ),
        migrations.CreateModel(
            name='Tour_Staff',
            fields=[
                ('tour_staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapp.staff')),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapp.tour')),
            ],
            options={
                'db_table': 'tour_staff',
            },
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tourapp.user'),
        ),
    ]
